In [4]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

In [7]:
print(x*y)

tensor([10.,  3.])


In [10]:
x = torch.zeros([2,5])


In [12]:
x
x.shape

torch.Size([2, 5])

In [14]:
y = torch.rand([2,5])


In [15]:
y

tensor([[0.3574, 0.4230, 0.3292, 0.4754, 0.0677],
        [0.5880, 0.4943, 0.8318, 0.5023, 0.1719]])

In [17]:
y.view([1,10])

tensor([[0.3574, 0.4230, 0.3292, 0.4754, 0.0677, 0.5880, 0.4943, 0.8318, 0.5023,
         0.1719]])

In [18]:
y

tensor([[0.3574, 0.4230, 0.3292, 0.4754, 0.0677],
        [0.5880, 0.4943, 0.8318, 0.5023, 0.1719]])